name: Release on tag
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install checkout deps
      working-directory: 'applications'
      run: 'bun install '
    - name: Build apps in dist
      working-directory: '.'
      run: 'make compile_apps'
    - name: Bump tag
      working-directory: '.'
      run: 'make update_version'
    - name: Compile Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'xprcheckout-webauth-gateway-for-e-commerce.zip'
        directory: '.'
        exclusions: '*.git* /*node_modules/* .editorconfig /*applications/*'
    - name: Generate JSON manifest
      run: 'VERSION=${{  github.ref_name }} make generate_manifest'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: '${{  github.ref_name }}'
        artifacts: "xprcheckout-webauth-gateway-for-e-commerce.zip,info.json"
        token: ${{ secrets.GITHUB_TOKEN }}