name: Release on tag
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install checkout deps
      working-directory: 'applications/apps/checkout'
      run: 'npm install'
    - name: Install refund deps
      working-directory: 'applications/apps/refund'
      run: 'npm install'
    - name: Install regstore deps
      working-directory: 'applications/apps/regstore'
      run: 'npm install'
    - name: Build apps in dist
      working-directory: '.'
      run: 'make compile_apps'
    - name: Compile Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'xprcheckout_woocomerce_gateway_beta_${{  github.ref_name }}.zip'
        directory: '.'
        exclusions: '*.git* /*node_modules/* .editorconfig /*applications/*'
    - name: Generate JSON manifest
      run: 'VERSION=${{  github.ref_name }} make generate_manifest'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: '${{  github.ref_name }}'
        artifacts: "xprcheckout_woocomerce_gateway_beta_${{  github.ref_name }}.zip,info.json"
        token: ${{ secrets.GITHUB_TOKEN }}