name: Release on tag
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install deps
      working-directory: './assets'
      run: 'npm install'
    - name: Build Svelte apps
      working-directory: './assets'
      run: 'npm run build'
    - name: Compile Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'xprcheckout_woocomerce_gateway_beta_${{  github.ref_name }}.zip'
        directory: '.'
        exclusions: '*.git* /*node_modules/* .editorconfig /*assets/*'
    - name: Generate JSON manifest
      run: 'VERSION=${{  github.ref_name }} make generate_manifest'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: '${{  github.ref_name }}'
        artifacts: "xprcheckout_woocomerce_gateway_beta_${{  github.ref_name }}.zip,info.json"
        token: ${{ secrets.GITHUB_TOKEN }}