# This is a basic workflow to help you get started with Actions

name: Release on tag

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - release
    #tags:
      #- "v*.*.*"
  # Allows you to run this workflow manually from the Actions tab
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install deps
        working-directory: './assets'
        run: 'npm install'
      - name: Build Svelte apps
        working-directory: './assets'
        run: 'npm run build'
      - name: Compile folder
        working-directory: './'
        run: 'make compile'
      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./wookey_woocommerce_webauth_gateway_0.9.13-beta.zip # the folder which has all the files that you want to release
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
